lsi: false
safe: true
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge 
# GitHub Pages settings
url: "https://liaddddd.github.io"
baseurl: ""
# SSL/HTTPS settings
enforce_ssl: true
# Build settings
future: false 